### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cjlcarvalho** [cjlcarvalho/ads-file-scraping#1]
- [x] Erro durante transição entre páginas
- [x] Erro ao acessar subdiretórios (por exemplo na página de BD)
- [x] Criar README explicando utilização
